[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  status = 200

[[headers]]
  for = "/graphql"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "POST"
      Access-Control-Allow-Headers = "Content-Type, Authorization"